#ifndef DSPXMODEL_DSPXMODELPROPERTYMAPPERGLOBAL_H
#define DSPXMODEL_DSPXMODELPROPERTYMAPPERGLOBAL_H

#include <QtGlobal>

#ifndef DSPXMODEL_PROPERTYMAPPER_EXPORT
#  ifdef DSPXMODEL_PROPERTYMAPPER_STATIC
#    define DSPXMODEL_PROPERTYMAPPER_EXPORT
#  else
#    ifdef DSPXMODEL_PROPERTYMAPPER_LIBRARY
#      define DSPXMODEL_PROPERTYMAPPER_EXPORT Q_DECL_EXPORT
#    else
#      define DSPXMODEL_PROPERTYMAPPER_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // DSPXMODEL_DSPXMODELPROPERTYMAPPERGLOBAL_H
