#ifndef DSPXMODEL_DSPXMODELSELECTIONMODELGLOBAL_H
#define DSPXMODEL_DSPXMODELSELECTIONMODELGLOBAL_H

#include <QtGlobal>

#ifndef DSPXMODEL_SELECTIONMODEL_EXPORT
#  ifdef DSPXMODEL_SELECTIONMODEL_STATIC
#    define DSPXMODEL_SELECTIONMODEL_EXPORT
#  else
#    ifdef DSPXMODEL_SELECTIONMODEL_LIBRARY
#      define DSPXMODEL_SELECTIONMODEL_EXPORT Q_DECL_EXPORT
#    else
#      define DSPXMODEL_SELECTIONMODEL_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // DSPXMODEL_DSPXMODELSELECTIONMODELGLOBAL_H
