#ifndef DSPXMODEL_DSPXMODELPIECEGLOBAL_H
#define DSPXMODEL_DSPXMODELPIECEGLOBAL_H

#include <QtGlobal>

#ifndef DSPXMODEL_PIECE_EXPORT
#  ifdef DSPXMODEL_PIECE_STATIC
#    define DSPXMODEL_PIECE_EXPORT
#  else
#    ifdef DSPXMODEL_PIECE_LIBRARY
#      define DSPXMODEL_PIECE_EXPORT Q_DECL_EXPORT
#    else
#      define DSPXMODEL_PIECE_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // DSPXMODEL_DSPXMODELPIECEGLOBAL_H
