#ifndef DSPXMODEL_DSPXMODELCOREGLOBAL_H
#define DSPXMODEL_DSPXMODELCOREGLOBAL_H

#include <QtGlobal>

#ifndef DSPXMODEL_CORE_EXPORT
#  ifdef DSPXMODEL_CORE_STATIC
#    define DSPXMODEL_CORE_EXPORT
#  else
#    ifdef DSPXMODEL_CORE_LIBRARY
#      define DSPXMODEL_CORE_EXPORT Q_DECL_EXPORT
#    else
#      define DSPXMODEL_CORE_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // DSPXMODEL_DSPXMODELCOREGLOBAL_H
